import torch
import numpy as np
import trimesh

# Load custom points
pcd = trimesh.load("data/tcp/point_clouds/human.ply")
custom_points = torch.tensor(pcd.vertices, dtype=torch.float32)

# Convert OpenGL to OpenCV
custom_points[:, 1] = -custom_points[:, 1]
custom_points[:, 2] = -custom_points[:, 2]

# depth_avg from cam_info.json is ~1.284, start_elevation=5.0
radius = 1.284
elevation_rad = np.deg2rad(5.0)

c2w_0 = torch.tensor([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, -radius],
                      [0, 0, 0, 1]], dtype=torch.float32)
R_elevation = torch.tensor([[1, 0, 0, 0],
                            [0, np.cos(-elevation_rad), -np.sin(-elevation_rad), 0],
                            [0, np.sin(-elevation_rad), np.cos(-elevation_rad), 0],
                            [0, 0, 0, 1]], dtype=torch.float32)
c2w_0 = R_elevation @ c2w_0

custom_points_world = (c2w_0[:3, :3] @ custom_points.T).T + c2w_0[:3, -1]

print("Custom Points Transformed Min:", custom_points_world.min(dim=0)[0])
print("Custom Points Transformed Max:", custom_points_world.max(dim=0)[0])
print("Custom Points Transformed Mean:", custom_points_world.mean(dim=0))

# Load the pcd.ply generated by cam_render.py to compare
pcd_ref = trimesh.load("outputs/human_selfpointcloud/pcd.ply")
ref_points = torch.tensor(pcd_ref.vertices, dtype=torch.float32)
print("Reference Points Min:", ref_points.min(dim=0)[0])
print("Reference Points Max:", ref_points.max(dim=0)[0])
print("Reference Points Mean:", ref_points.mean(dim=0))

